### ISSUE TITLE
Fail to build with glibc 2.23 because of _BSD_SOURCE without _DEFAULT_SOURCE

### ISSUE THREAD

**Issue by petterreinholdtsen** [unioslo/tsdfx#115]
When trying to build tsdfx using Debian Unstable with glibc 2.23, the build fail like this:

```
In file included from /usr/include/endian.h:21:0,
                 from tsd_sha1.c:44:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
```

The issue is described in http://stackoverflow.com/questions/29201515/what-does-d-default-source-do
and https://lwn.net/Articles/590381/ .  A quick fix is to also define _DEFAULT_SOURCE, but I also tested to remove the '#include &lt;endian.h>' statement completely and the code build without it.  Why is the header file included in the first place?

**Comment by dag-erling** [comment]
Because that is where `htobe32()` and `be32toh()` are defined. If the code builds without those headers, something else is pulling them in behind the scenes, which is a bug in either Linux or glibc.
